require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Zanysound' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'react-native-track-player', :path => '../node_modules/react-native-track-player'

  pod 'react-native-blur', :path => '../node_modules/@react-native-community/blur'

  pod 'RNCMaskedView', :path => '../node_modules/@react-native-community/masked-view'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  target 'ZanysoundTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Zanysound-tvOS' do
  # Pods for Zanysound-tvOS

  target 'Zanysound-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
