const MOBILE_MAX_WIDTH = 480;
const SMALL_TABLET_MIN_WIDTH = 481;
const SMALL_TABLET_MAX_WIDTH = 767;
const TABLET_MIN_WIDTH = 768;
const TABLET_MAX_WIDTH = 1024;

module.exports = {
  MOBILE_MAX_WIDTH,
  SMALL_TABLET_MIN_WIDTH,
  SMALL_TABLET_MAX_WIDTH,
  TABLET_MIN_WIDTH,
  TABLET_MAX_WIDTH,
};
